/*
 * This file is generated by jOOQ.
*/
package com.jooq.db;


import com.jooq.db.tables.Employe;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in comm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>comm.employe</code>.
     */
    public static final Employe EMPLOYE = com.jooq.db.tables.Employe.EMPLOYE;
}
